### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by morenodercoli** [marcbachmann/localized-countries#2]
This library seems very good, but there is no license and in Github Projects this means it's closed source.
Is this the correct behaviour or you wanted to share with the community?

**Comment by marcbachmann** [comment]
No, this is open source and the license is ISC.
I've only defined that in the package.json file.
https://github.com/marcbachmann/localized-countries/blob/master/package.json#L12

**Comment by morenodercoli** [comment]
Ok, thank you for your work
