### ISSUE TITLE
German country BW is spelled wrong

### ISSUE THREAD

**Issue by jfm-efarm** [marcbachmann/localized-countries#3]
"BW":"Botsuana" is meant to be "Botswana"

**Comment by marcbachmann** [comment]
Weird, in `de_CH` it is correct 😕

**Comment by marcbachmann** [comment]
Oh, https://de.wikipedia.org/wiki/Botswana

> Botswana bzw. in Langform Republik Botswana [bɔˈtsu̯aːna] (nach amtlicher[7][8] deutscher Schreibweise Botsuana), ist ein Binnenstaat im südlichen Afrika.

**Comment by jfm-efarm** [comment]
Oh, never seen that. Seems to be official tho. Sorry for that
